# Generated by Django 5.0.6 on 2024-05-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='historyStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_title', models.CharField(max_length=200)),
                ('asset_qty', models.IntegerField()),
                ('asset_buydate', models.DateTimeField(verbose_name='date bought')),
                ('asset_selldate', models.DateTimeField(verbose_name='date sold')),
            ],
        ),
    ]
