# Generated by Django 5.0.6 on 2024-05-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historystorage',
            name='asset_totaldollars',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
