# Generated by Django 5.0.6 on 2024-05-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_historystorage_asset_totaldollars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historystorage',
            name='asset_buydate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='historystorage',
            name='asset_selldate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
