# Generated by Django 5.0.6 on 2024-05-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_historystorage_asset_buydate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historystorage',
            name='hash_field',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
