# Generated by Django 5.0.6 on 2024-05-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_historystorage_hash_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='historystorage',
            name='asset_price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
