# Generated by Django 5.0.6 on 2024-05-15 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_historystorage_asset_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historystorage',
            name='asset_buydate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
