# Generated by Django 5.0.6 on 2024-05-15 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_historystorage_asset_buydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='historystorage',
            name='asset_qtysold',
            field=models.IntegerField(default=0),
        ),
    ]
