# Generated by Django 5.0.6 on 2024-05-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_historystorage_asset_qtysold'),
    ]

    operations = [
        migrations.AddField(
            model_name='historystorage',
            name='asset_sell_considered',
            field=models.BooleanField(default=False),
        ),
    ]
