# Generated by Django 5.0.6 on 2024-05-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_historystorage_asset_sell_considered'),
    ]

    operations = [
        migrations.AddField(
            model_name='historystorage',
            name='asset_soldprice',
            field=models.FloatField(default=0.0),
        ),
    ]
